"""
PDF Renderer
=============
Generates professional PDF reports from structured content.
Uses fpdf2 for PDF generation.

Install: pip install fpdf2
"""

from pathlib import Path


class PDFRenderer:
    """Renders professional PDF reports."""

    def render(self, filepath, title="Report", content="", sections=None, 
               author="Nanoclaw AI", **kwargs):
        """
        Generate a PDF report.
        
        Args:
            filepath: Output path
            title: Report title
            content: Main content (markdown-ish text)
            sections: Optional list of {"title": str, "content": str}
            author: Author name
        """
        try:
            from fpdf import FPDF
        except ImportError:
            raise ImportError("Install fpdf2: pip install fpdf2")

        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=20)

        # --- Cover Page ---
        pdf.add_page()
        pdf.set_fill_color(15, 15, 35)
        pdf.rect(0, 0, 210, 297, 'F')
        
        pdf.set_font("Helvetica", "B", 28)
        pdf.set_text_color(0, 210, 255)
        pdf.ln(60)
        pdf.cell(0, 20, title, new_x="LMARGIN", new_y="NEXT", align="C")
        
        pdf.set_font("Helvetica", "", 12)
        pdf.set_text_color(160, 160, 200)
        pdf.ln(10)
        pdf.cell(0, 10, f"Generated by {author}", new_x="LMARGIN", new_y="NEXT", align="C")
        
        from datetime import datetime
        pdf.cell(0, 10, datetime.now().strftime("%B %d, %Y"), new_x="LMARGIN", new_y="NEXT", align="C")

        # --- Content Pages ---
        pdf.add_page()
        pdf.set_fill_color(255, 255, 255)
        pdf.set_text_color(30, 30, 30)

        if sections:
            for sec in sections:
                pdf.set_font("Helvetica", "B", 16)
                pdf.set_text_color(0, 100, 180)
                pdf.cell(0, 12, sec["title"], new_x="LMARGIN", new_y="NEXT")
                pdf.ln(2)
                
                pdf.set_font("Helvetica", "", 11)
                pdf.set_text_color(30, 30, 30)
                for line in sec["content"].split('\n'):
                    line = line.strip()
                    if line.startswith('- '):
                        pdf.cell(8)
                        pdf.cell(0, 7, f"\u2022 {line[2:]}", new_x="LMARGIN", new_y="NEXT")
                    elif line:
                        pdf.multi_cell(0, 7, line)
                    else:
                        pdf.ln(3)
                pdf.ln(5)
        elif content:
            self._render_content(pdf, content)

        pdf.output(filepath)
        return {"renderer": "pdf_renderer", "pages": pdf.page}

    def _render_content(self, pdf, content):
        """Parse markdown-ish content into PDF elements."""
        for line in content.split('\n'):
            line = line.strip()
            
            if line.startswith('# '):
                pdf.set_font("Helvetica", "B", 18)
                pdf.set_text_color(0, 100, 180)
                pdf.cell(0, 12, line[2:], new_x="LMARGIN", new_y="NEXT")
                pdf.set_text_color(30, 30, 30)
            elif line.startswith('## '):
                pdf.set_font("Helvetica", "B", 15)
                pdf.set_text_color(0, 80, 160)
                pdf.cell(0, 10, line[3:], new_x="LMARGIN", new_y="NEXT")
                pdf.set_text_color(30, 30, 30)
            elif line.startswith('### '):
                pdf.set_font("Helvetica", "B", 13)
                pdf.cell(0, 9, line[4:], new_x="LMARGIN", new_y="NEXT")
            elif line.startswith('- '):
                pdf.set_font("Helvetica", "", 11)
                pdf.cell(8)
                pdf.cell(0, 7, f"\u2022 {line[2:]}", new_x="LMARGIN", new_y="NEXT")
            elif line.startswith('**') and line.endswith('**'):
                pdf.set_font("Helvetica", "B", 11)
                pdf.cell(0, 7, line.strip('*'), new_x="LMARGIN", new_y="NEXT")
            elif line.startswith('|'):
                # Skip table formatting (too complex for basic PDF)
                pdf.set_font("Courier", "", 9)
                pdf.cell(0, 6, line, new_x="LMARGIN", new_y="NEXT")
            elif line:
                pdf.set_font("Helvetica", "", 11)
                pdf.multi_cell(0, 7, line)
            else:
                pdf.ln(3)
