#!/usr/bin/env python3
"""
Example: Create a custom agent from the agent-pocketflow template.

Shows how to:
1. Create custom nodes
2. Wire them into a flow
3. Run with dashboard
"""

import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "scripts"))

from nodes.base_node import BaseNode
from nodes.llm_node import LLMNode
from flow import Flow


# ─── Step 1: Create custom nodes ──────────────────────────────────

class FetchDataNode(BaseNode):
    """Simulates fetching data from an API."""
    def __init__(self):
        super().__init__("fetch_data")

    def exec(self, context):
        # Simulate API fetch
        context["raw_data"] = {
            "users": 1250,
            "revenue": 45000,
            "churn_rate": 3.2,
            "nps_score": 72,
        }
        print("    📊 Fetched metrics from API")
        return context["raw_data"]


class AnalyzeNode(LLMNode):
    """Analyzes data using LLM."""
    def __init__(self, test_mode=True):
        super().__init__(
            name="analyze_metrics",
            prompt_template="Analyze these SaaS metrics and provide insights:\n{data}",
            context_keys=["raw_data"],
            output_key="analysis",
            test_mode=test_mode,
        )

    def exec(self, context):
        data = context.get("raw_data", {})
        if self.test_mode:
            context["analysis"] = (
                f"📈 Analysis: {data.get('users', 0)} users, "
                f"${data.get('revenue', 0)} revenue, "
                f"{data.get('churn_rate', 0)}% churn. "
                f"NPS: {data.get('nps_score', 0)}. Overall: healthy growth."
            )
        else:
            context["analysis"] = self.llm.generate_text(
                self.prompt_template.format(data=str(data))
            )
        return context["analysis"]


class ReportNode(BaseNode):
    """Generates a summary report."""
    def __init__(self):
        super().__init__("generate_report")

    def exec(self, context):
        analysis = context.get("analysis", "No analysis available")
        data = context.get("raw_data", {})

        report = f"""# SaaS Metrics Report

## Key Metrics
- Users: {data.get('users', 'N/A')}
- Revenue: ${data.get('revenue', 'N/A')}
- Churn: {data.get('churn_rate', 'N/A')}%
- NPS: {data.get('nps_score', 'N/A')}

## Analysis
{analysis}

## Generated by Agent PocketFlow
"""
        context["report"] = report
        print(f"    📝 Report generated ({len(report)} chars)")
        return report


# ─── Step 2: Wire into a flow ────────────────────────────────────

def main():
    print("\n🔷 Custom Agent Example — SaaS Metrics Analyzer\n")

    flow = Flow([
        FetchDataNode(),
        AnalyzeNode(test_mode=True),
        ReportNode(),
    ], name="SaaS Metrics Analyzer")

    # Step 3: Run!
    result = flow.run()

    # Print report
    if result["flow"]["status"] == "completed":
        print("\n" + "=" * 60)
        print(result.get("report", "No report"))
        print("=" * 60)


if __name__ == "__main__":
    main()
