#!/usr/bin/env npx tsx
/**
 * UI Style Generator — Markdown formatter
 * Usage: npx tsx generate_markdown.ts design-system.json [output.md]
 *
 * Reads a DesignSystem JSON file and outputs a Markdown styleguide.
 */

import * as fs from "fs";
import * as path from "path";

interface ColorScheme {
  primary: string;
  primaryHover: string;
  secondary: string;
  surface: string;
  surfaceHighlight: string;
  background: string;
  text: string;
  textSecondary: string;
  border: string;
  success: string;
  warning: string;
  error: string;
}

interface DesignSystem {
  projectName: string;
  description: string;
  colors: { light: ColorScheme; dark: ColorScheme };
  gradients: { primary: string; secondary: string };
  typography: {
    fontFamily: string;
    scale: { h1: string; h2: string; h3: string; body: string; caption: string };
  };
  spacing: {
    base: number;
    scale: { xs: string; sm: string; md: string; lg: string; xl: string; xxl: string };
  };
  animation: {
    easing: string;
    duration: { fast: string; normal: string; slow: string };
  };
  layout: { containerWidth: string; gridColumns: number; gridGap: string };
  effects: { glass: string; borderWidth: string };
  iconStyle: string;
  borderRadius: { small: string; medium: string; large: string; full: string };
  shadows: { sm: string; md: string; lg: string };
}

const colorRow = (label: string, hex: string) =>
  `| **${label}** | \`${hex}\` | <span style="display:inline-block;width:40px;height:16px;background:${hex};border:1px solid #ccc;border-radius:3px;vertical-align:middle"></span> |`;

const generateMarkdown = (ds: DesignSystem): string => {
  const { light, dark } = ds.colors;
  return `# ${ds.projectName} - UI Styleguide
Generated by Claude AI

> ${ds.description}

---

## 🎨 Color Tokens

### Light Mode

| Token | Hex | Preview |
|-------|-----|---------|
${colorRow("Primary", light.primary)}
${colorRow("Primary Hover", light.primaryHover)}
${colorRow("Secondary", light.secondary)}
${colorRow("Surface", light.surface)}
${colorRow("Surface Highlight", light.surfaceHighlight)}
${colorRow("Background", light.background)}
${colorRow("Text", light.text)}
${colorRow("Text Secondary", light.textSecondary)}
${colorRow("Border", light.border)}
${colorRow("Success", light.success)}
${colorRow("Warning", light.warning)}
${colorRow("Error", light.error)}

### Dark Mode

| Token | Hex | Preview |
|-------|-----|---------|
${colorRow("Primary", dark.primary)}
${colorRow("Primary Hover", dark.primaryHover)}
${colorRow("Secondary", dark.secondary)}
${colorRow("Surface", dark.surface)}
${colorRow("Surface Highlight", dark.surfaceHighlight)}
${colorRow("Background", dark.background)}
${colorRow("Text", dark.text)}
${colorRow("Text Secondary", dark.textSecondary)}
${colorRow("Border", dark.border)}
${colorRow("Success", dark.success)}
${colorRow("Warning", dark.warning)}
${colorRow("Error", dark.error)}

### Gradients

| Name | Value |
|------|-------|
| Primary | \`${ds.gradients.primary}\` |
| Secondary | \`${ds.gradients.secondary}\` |

---

## ✒️ Typography

**Font Family**: \`${ds.typography.fontFamily}\`
**Icon Style**: \`${ds.iconStyle}\`

| Scale | Size | Usage |
|-------|------|-------|
| H1 | ${ds.typography.scale.h1} | Page Titles |
| H2 | ${ds.typography.scale.h2} | Section Headers |
| H3 | ${ds.typography.scale.h3} | Sub-sections |
| Body | ${ds.typography.scale.body} | Main Content |
| Caption | ${ds.typography.scale.caption} | Small text, labels |

---

## 📐 Layout & Structure

| Property | Value |
|----------|-------|
| Max Width | \`${ds.layout.containerWidth}\` |
| Grid Columns | \`${ds.layout.gridColumns}\` |
| Grid Gap | \`${ds.layout.gridGap}\` |
| Border Width | \`${ds.effects.borderWidth}\` |

**Effects**: Glass Blur: \`${ds.effects.glass}\`

---

## ⚡ Motion & Spacing

**Easing**: \`${ds.animation.easing}\`

| Speed | Duration |
|-------|----------|
| Fast | \`${ds.animation.duration.fast}\` |
| Normal | \`${ds.animation.duration.normal}\` |
| Slow | \`${ds.animation.duration.slow}\` |

**Base Unit**: ${ds.spacing.base}px

| Token | Size |
|-------|------|
| XS | \`${ds.spacing.scale.xs}\` |
| SM | \`${ds.spacing.scale.sm}\` |
| MD | \`${ds.spacing.scale.md}\` |
| LG | \`${ds.spacing.scale.lg}\` |
| XL | \`${ds.spacing.scale.xl}\` |
| XXL | \`${ds.spacing.scale.xxl}\` |

---

## 🔲 Radius & Elevation

### Border Radius
- **Small**: \`${ds.borderRadius.small}\`
- **Medium**: \`${ds.borderRadius.medium}\`
- **Large**: \`${ds.borderRadius.large}\`
- **Full**: \`${ds.borderRadius.full}\`

### Shadows
- **Small**: \`${ds.shadows.sm}\`
- **Medium**: \`${ds.shadows.md}\`
- **Large**: \`${ds.shadows.lg}\`

---

## 💻 CSS Variables

\`\`\`css
:root {
  /* Colors — Light Mode */
  --primary: ${light.primary};
  --primary-hover: ${light.primaryHover};
  --secondary: ${light.secondary};
  --surface: ${light.surface};
  --surface-highlight: ${light.surfaceHighlight};
  --background: ${light.background};
  --text: ${light.text};
  --text-secondary: ${light.textSecondary};
  --border: ${light.border};
  --success: ${light.success};
  --warning: ${light.warning};
  --error: ${light.error};

  /* Gradients */
  --gradient-primary: ${ds.gradients.primary};
  --gradient-secondary: ${ds.gradients.secondary};

  /* Typography */
  --font-family: '${ds.typography.fontFamily}', sans-serif;
  --text-h1: ${ds.typography.scale.h1};
  --text-h2: ${ds.typography.scale.h2};
  --text-h3: ${ds.typography.scale.h3};
  --text-body: ${ds.typography.scale.body};
  --text-caption: ${ds.typography.scale.caption};

  /* Spacing */
  --space-xs: ${ds.spacing.scale.xs};
  --space-sm: ${ds.spacing.scale.sm};
  --space-md: ${ds.spacing.scale.md};
  --space-lg: ${ds.spacing.scale.lg};
  --space-xl: ${ds.spacing.scale.xl};
  --space-xxl: ${ds.spacing.scale.xxl};

  /* Layout */
  --max-width: ${ds.layout.containerWidth};
  --grid-cols: ${ds.layout.gridColumns};
  --grid-gap: ${ds.layout.gridGap};

  /* Effects */
  --glass-blur: ${ds.effects.glass};
  --border-width: ${ds.effects.borderWidth};

  /* Border Radius */
  --radius-sm: ${ds.borderRadius.small};
  --radius-md: ${ds.borderRadius.medium};
  --radius-lg: ${ds.borderRadius.large};
  --radius-full: ${ds.borderRadius.full};

  /* Shadows */
  --shadow-sm: ${ds.shadows.sm};
  --shadow-md: ${ds.shadows.md};
  --shadow-lg: ${ds.shadows.lg};

  /* Motion */
  --ease-default: ${ds.animation.easing};
  --duration-fast: ${ds.animation.duration.fast};
  --duration-normal: ${ds.animation.duration.normal};
  --duration-slow: ${ds.animation.duration.slow};
}

[data-theme='dark'] {
  --primary: ${dark.primary};
  --primary-hover: ${dark.primaryHover};
  --secondary: ${dark.secondary};
  --surface: ${dark.surface};
  --surface-highlight: ${dark.surfaceHighlight};
  --background: ${dark.background};
  --text: ${dark.text};
  --text-secondary: ${dark.textSecondary};
  --border: ${dark.border};
  --success: ${dark.success};
  --warning: ${dark.warning};
  --error: ${dark.error};
}
\`\`\`
`;
};

// CLI entry point
const inputFile = process.argv[2];
const outputFile = process.argv[3];

if (!inputFile) {
  console.error("Usage: npx tsx generate_markdown.ts <design-system.json> [output.md]");
  process.exit(1);
}

const raw = fs.readFileSync(path.resolve(inputFile), "utf-8");
const ds: DesignSystem = JSON.parse(raw);
const markdown = generateMarkdown(ds);

if (outputFile) {
  fs.writeFileSync(path.resolve(outputFile), markdown, "utf-8");
  console.log(`✅ Styleguide written to ${outputFile}`);
} else {
  console.log(markdown);
}
